import React from 'react'
import Head from 'next/head'
import TopNav from '../components/lighthouse/TopNav'
import Header from '../components/header/Header'
import HomePage from '../components/homepage/Home'
import MobileNav from '../components/mobile-menu/MobileNav'


const Home = () => {
  return (
    <div>
      <Head>
        <title>Maya.com: Fashion, Phones, Perfumes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileNav />
      <TopNav />
      <Header />
      <div id="root">
        <HomePage />
      </div>
    </div>
  )
}

export default Home